var h=Object.defineProperty;var D=Object.getOwnPropertyDescriptor;var P=Object.getOwnPropertyNames;var Y=Object.prototype.hasOwnProperty;var F=(o,s)=>{for(var t in s)h(o,t,{get:s[t],enumerable:!0})},x=(o,s,t,e)=>{if(s&&typeof s=="object"||typeof s=="function")for(let n of P(s))!Y.call(o,n)&&n!==t&&h(o,n,{get:()=>s[n],enumerable:!(e=D(s,n))||e.enumerable});return o};var b=o=>x(h({},"__esModule",{value:!0}),o);var I={};F(I,{default:()=>u});module.exports=b(I);var c=require("obsidian");function v(o){var i,a;let s=o.app.internalPlugins,t="YYYY-MM-DD",e="",n="";if(s){let l=(i=s.getPluginById)==null?void 0:i.call(s,"daily-notes");if((a=l==null?void 0:l.instance)!=null&&a.options){let d=l.instance.options;t=d.format||t,e=d.folder||e,n=d.template||n}}return{format:t,folder:e,template:n}}function g(o,s,t){let e=o.format(s);return t?`${t}/${e}`:e}function C(o,s){let t=o.split(`
`),e=!1,n=[];for(let i of t){if(/^#{1,6}\s/.test(i)){e=i.trim().toLowerCase()===s.trim().toLowerCase();continue}e&&/^(\s*)-\s\[ \]\s/.test(i)&&n.push(i)}return n}function T(o){return o.replace(/^\s*-\s\[.\]\s*/,"").trim()}function M(o,s,t){if(t.length===0)return o;let e=o.split(`
`),n=new Set,i=-1,a=-1,l=!1;for(let r=0;r<e.length;r++){if(/^#{1,6}\s/.test(e[r])){if(l)break;e[r].trim().toLowerCase()===s.trim().toLowerCase()&&(i=r,l=!0);continue}if(!l)continue;let p=e[r].trim();/^-\s\[.\]\s/.test(p)?(n.add(T(p)),a=r):/^\s+-/.test(e[r])&&a!==-1&&(a=r)}let d=t.filter(r=>!n.has(T(r)));if(d.length===0)return o;if(i===-1){let r=(o.endsWith(`
`)?"":`
`)+`
`+s+`
`+d.join(`
`)+`
`;return o+r}let f=a!==-1?a:i,m=d.join(`
`);return e.splice(f+1,0,m),e.join(`
`)}async function A(o,s,t,e,n=30){for(let i=1;i<=n;i++){let a=s.clone().subtract(i,"days"),l=g(a,t,e)+".md",d=o.app.vault.getAbstractFileByPath(l);if(d instanceof c.TFile)return d}return null}var w="## Todo",u=class extends c.Plugin{constructor(){super(...arguments);this.processedToday=!1;this.lastProcessedDate=""}async onload(){this.addCommand({id:"rollover-todos-now",name:"Rollover todos from previous daily note",callback:()=>this.rolloverTodos(!0)}),this.registerEvent(this.app.workspace.on("file-open",t=>{t&&this.onFileOpen(t)}))}async onFileOpen(t){let{format:e,folder:n}=v(this),i=(0,c.moment)(),a=g(i,e,n)+".md";if(t.path!==a)return;let l=i.format("YYYY-MM-DD");this.processedToday&&this.lastProcessedDate===l||await this.rolloverTodos(!1)}async rolloverTodos(t){let{format:e,folder:n}=v(this),i=(0,c.moment)(),a=i.format("YYYY-MM-DD"),l=g(i,e,n)+".md",d=this.app.vault.getAbstractFileByPath(l);if(!(d instanceof c.TFile)){t&&new c.Notice("Today's daily note does not exist yet.");return}let f=await A(this,i,e,n);if(!f){t&&new c.Notice("No previous daily note found (searched last 30 days).");return}let m=await this.app.vault.read(f),r=C(m,w);if(r.length===0){t&&new c.Notice("No unchecked todos found in the previous daily note."),this.processedToday=!0,this.lastProcessedDate=a;return}let p=await this.app.vault.read(d),y=M(p,w,r);y!==p?(await this.app.vault.modify(d,y),new c.Notice(`Rolled over ${r.length} todo(s) from ${f.basename}.`)):t&&new c.Notice("All todos already present \u2014 nothing to roll over."),this.processedToday=!0,this.lastProcessedDate=a}};
