var m=Object.defineProperty;var w=Object.getOwnPropertyDescriptor;var D=Object.getOwnPropertyNames;var P=Object.prototype.hasOwnProperty;var Y=(n,o)=>{for(var t in o)m(n,t,{get:o[t],enumerable:!0})},F=(n,o,t,e)=>{if(o&&typeof o=="object"||typeof o=="function")for(let s of D(o))!P.call(n,s)&&s!==t&&m(n,s,{get:()=>o[s],enumerable:!(e=w(o,s))||e.enumerable});return n};var x=n=>F(m({},"__esModule",{value:!0}),n);var I={};Y(I,{default:()=>u});module.exports=x(I);var d=require("obsidian");function v(n){var i,c;let o=n.app.internalPlugins,t="YYYY-MM-DD",e="",s="";if(o){let a=(i=o.getPluginById)==null?void 0:i.call(o,"daily-notes");if((c=a==null?void 0:a.instance)!=null&&c.options){let l=a.instance.options;t=l.format||t,e=l.folder||e,s=l.template||s}}return{format:t,folder:e,template:s}}function g(n,o,t){let e=n.format(o);return t?`${t}/${e}`:e}function b(n,o){let t=n.split(`
`),e=!1,s=[];for(let i of t){if(/^#{1,6}\s/.test(i)){e=i.trim().toLowerCase()===o.trim().toLowerCase();continue}e&&/^(\s*)-\s\[ \]\s/.test(i)&&s.push(i)}return s}function C(n,o,t){if(t.length===0)return n;let e=n.split(`
`),s=new Set,i=-1,c=-1,a=!1;for(let r=0;r<e.length;r++){if(/^#{1,6}\s/.test(e[r])){if(a){c=r;break}e[r].trim().toLowerCase()===o.trim().toLowerCase()&&(i=r,a=!0);continue}if(a){let p=e[r].trim();p.length>0&&s.add(p)}}let l=t.filter(r=>!s.has(r.trim()));if(l.length===0)return n;if(i===-1){let r=(n.endsWith(`
`)?"":`
`)+`
`+o+`
`+l.join(`
`)+`
`;return n+r}let f=c===-1?e.length:c,h=l.join(`
`);return e.splice(f,0,h),e.join(`
`)}async function M(n,o,t,e,s=30){for(let i=1;i<=s;i++){let c=o.clone().subtract(i,"days"),a=g(c,t,e)+".md",l=n.app.vault.getAbstractFileByPath(a);if(l instanceof d.TFile)return l}return null}var T="## Todo",u=class extends d.Plugin{constructor(){super(...arguments);this.processedToday=!1;this.lastProcessedDate=""}async onload(){this.addCommand({id:"rollover-todos-now",name:"Rollover todos from previous daily note",callback:()=>this.rolloverTodos(!0)}),this.registerEvent(this.app.workspace.on("file-open",t=>{t&&this.onFileOpen(t)}))}async onFileOpen(t){let{format:e,folder:s}=v(this),i=(0,d.moment)(),c=g(i,e,s)+".md";if(t.path!==c)return;let a=i.format("YYYY-MM-DD");this.processedToday&&this.lastProcessedDate===a||await this.rolloverTodos(!1)}async rolloverTodos(t){let{format:e,folder:s}=v(this),i=(0,d.moment)(),c=i.format("YYYY-MM-DD"),a=g(i,e,s)+".md",l=this.app.vault.getAbstractFileByPath(a);if(!(l instanceof d.TFile)){t&&new d.Notice("Today's daily note does not exist yet.");return}let f=await M(this,i,e,s);if(!f){t&&new d.Notice("No previous daily note found (searched last 30 days).");return}let h=await this.app.vault.read(f),r=b(h,T);if(r.length===0){t&&new d.Notice("No unchecked todos found in the previous daily note."),this.processedToday=!0,this.lastProcessedDate=c;return}let p=await this.app.vault.read(l),y=C(p,T,r);y!==p?(await this.app.vault.modify(l,y),new d.Notice(`Rolled over ${r.length} todo(s) from ${f.basename}.`)):t&&new d.Notice("All todos already present \u2014 nothing to roll over."),this.processedToday=!0,this.lastProcessedDate=c}};
