var g=Object.defineProperty;var P=Object.getOwnPropertyDescriptor;var x=Object.getOwnPropertyNames;var Y=Object.prototype.hasOwnProperty;var b=(o,i)=>{for(var n in i)g(o,n,{get:i[n],enumerable:!0})},F=(o,i,n,t)=>{if(i&&typeof i=="object"||typeof i=="function")for(let r of x(i))!Y.call(o,r)&&r!==n&&g(o,r,{get:()=>i[r],enumerable:!(t=P(i,r))||t.enumerable});return o};var C=o=>F(g({},"__esModule",{value:!0}),o);var A={};b(A,{default:()=>m});module.exports=C(A);var f=require("obsidian");function T(o){var s,l;let i=o.app.internalPlugins,n="YYYY-MM-DD",t="",r="";if(i){let d=(s=i.getPluginById)==null?void 0:s.call(i,"daily-notes");if((l=d==null?void 0:d.instance)!=null&&l.options){let a=d.instance.options;n=a.format||n,t=a.folder||t,r=a.template||r}}return{format:n,folder:t,template:r}}function h(o,i,n){let t=o.format(i);return n?`${n}/${t}`:t}function M(o,i){let n=o.split(`
`),t=!1,r=[];for(let s of n){if(/^#{1,6}\s/.test(s)){t=s.trim().toLowerCase()===i.trim().toLowerCase();continue}t&&/^(\s*)-\s\[ \]\s/.test(s)&&s.replace(/^\s*-\s\[ \]\s*/,"").trim().length>0&&r.push(s)}return r}function w(o){return o.replace(/^\s*-\s\[.\]\s*/,"").trim()}function k(o,i,n){if(n.length===0)return{result:o,added:0};let t=o.split(`
`),r=new Set,s=-1,l=-1,d=!1;for(let e=0;e<t.length;e++){if(/^#{1,6}\s/.test(t[e])){if(d)break;t[e].trim().toLowerCase()===i.trim().toLowerCase()&&(s=e,d=!0);continue}if(!d)continue;let u=t[e].trim();/^-\s\[.\]\s/.test(u)?(r.add(w(u)),l=e):/^\s+-/.test(t[e])&&l!==-1&&(l=e)}let a=n.filter(e=>!r.has(w(e)));if(a.length===0)return{result:o,added:0};if(s!==-1)for(let e=t.length-1;e>s&&!/^#{1,6}\s/.test(t[e]);e--)/^\s*-\s\[ \]\s*$/.test(t[e])&&(t.splice(e,1),l>=e&&l--);if(s===-1){let e=(o.endsWith(`
`)?"":`
`)+`
`+i+`
`+a.join(`
`)+`
`;return{result:o+e,added:a.length}}let c=s;for(let e=s+1;e<t.length&&!/^#{1,6}\s/.test(t[e]);e++){let u=t[e].trim();(/^-\s\[.\]\s/.test(u)||/^\s+-/.test(t[e])&&c>s)&&(c=e)}let p=a.join(`
`);return t.splice(c+1,0,p),{result:t.join(`
`),added:a.length}}async function I(o,i,n,t,r=30){for(let s=1;s<=r;s++){let l=i.clone().subtract(s,"days"),d=h(l,n,t)+".md",a=o.app.vault.getAbstractFileByPath(d);if(a instanceof f.TFile)return a}return null}var D="## Todo",m=class extends f.Plugin{constructor(){super(...arguments);this.processedToday=!1;this.lastProcessedDate=""}async onload(){this.addCommand({id:"rollover-todos-now",name:"Rollover todos from previous daily note",callback:()=>this.rolloverTodos(!0)}),this.registerEvent(this.app.workspace.on("file-open",n=>{n&&this.onFileOpen(n)}))}async onFileOpen(n){let{format:t,folder:r}=T(this),s=(0,f.moment)(),l=h(s,t,r)+".md";if(n.path!==l)return;let d=s.format("YYYY-MM-DD");this.processedToday&&this.lastProcessedDate===d||await this.rolloverTodos(!1)}async rolloverTodos(n){let{format:t,folder:r}=T(this),s=(0,f.moment)(),l=s.format("YYYY-MM-DD"),d=h(s,t,r)+".md",a=this.app.vault.getAbstractFileByPath(d);if(!(a instanceof f.TFile)){n&&new f.Notice("Today's daily note does not exist yet.");return}let c=await I(this,s,t,r);if(!c){n&&new f.Notice("No previous daily note found (searched last 30 days).");return}let p=await this.app.vault.read(c),e=M(p,D),u=await this.app.vault.read(a),{result:y,added:v}=k(u,D,e);y!==u&&await this.app.vault.modify(a,y),v>0&&new f.Notice(`Rolled over ${v} todo(s) from ${c.basename}.`),this.processedToday=!0,this.lastProcessedDate=l}};
